# Generated by Django 5.1.6 on 2025-03-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpiritualEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('faith', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.TextField()),
                ('organizer', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
            ],
        ),
    ]
